// src/components/ReportDocument.jsx
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Optional custom font
Font.register({
  family: "Inter",
  src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTm4VFw.ttf",
});

const styles = StyleSheet.create({
  page: {
    fontFamily: "Inter",
    padding: 32,
    fontSize: 12,
    color: "#111827",
  },
  header: { textAlign: "center", marginBottom: 20 },
  title: { fontSize: 20, fontWeight: "bold", color: "#4338CA" },
  subtitle: { fontSize: 14, marginTop: 4, color: "#4B5563" },
  section: { marginVertical: 12 },
  themeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  themeText: { fontWeight: "bold", color: "#1F2937" },
  percentText: { color: "#2563EB" },
  overall: { textAlign: "center", marginVertical: 20 },
  footer: { textAlign: "center", marginTop: 20, fontSize: 10, color: "#6B7280" },
});

export default function ReportDocument({ results }) {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Mastering Money Report</Text>
          <Text style={styles.subtitle}>Your Personalised Results</Text>
        </View>

        <View style={styles.overall}>
          <Text style={{ fontSize: 16 }}>
            Overall Score: {results.overallPercent}%
          </Text>
          <Text style={{ fontSize: 14 }}>{results.rating}</Text>
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 14, marginBottom: 6, color: "#4338CA" }}>
            Theme Scores
          </Text>
          {results.themes?.map((t) => (
            <View key={t.themeId} style={styles.themeRow}>
              <Text style={styles.themeText}>{t.themeName}</Text>
              <Text style={styles.percentText}>{t.percent}%</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 14, marginBottom: 6, color: "#4338CA" }}>
            Notes
          </Text>
          <Text>
            This report summarises your responses and scores. Higher percentages
            indicate stronger money skills within that theme.
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by Mastering Your Money App — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
